package io.github.qwzhang01.agent.core.run;

import java.time.Instant;
import java.util.Set;
import java.util.UUID;
import java.util.function.Consumer;

/**
 * Immutable execution context for one run (Stage 1.1 of the harness roadmap).
 * <p>
 * Replaces the scattered identity plumbing of v0.1.3: {@code runId} in
 * {@code NodeContext}, free strings for tenant/user, no trace correlation,
 * no deadline, no cancellation. One {@code Agent} or {@code RunManager}
 * execution binds exactly one RunContext; every downstream boundary (model
 * call, tool execution, memory read, sandbox run) receives the same
 * instance and must not re-derive identity on its own.
 * <p>
 * <b>Anti-forgery boundary (roadmap 1.1).</b> Fields split into two groups:
 * <ul>
 *   <li><b>System-generated</b> - runId, traceId (when not supplied),
 *       startedAt. Generated by the builder, never accepted from callers.</li>
 *   <li><b>Entry-supplied</b> - tenantId, userId, agentId, workflowId,
 *       channelId, parentRunId. These describe facts the entry adapter
 *       knows (who is calling, from which channel, continuing which run).
 *       They are constructor arguments, not model-visible strings: a Tool
 *       receiving the context cannot mint a different tenantId than the
 *       one its run was started with - the record is immutable and handed
 *       down, never re-created downstream.</li>
 * </ul>
 * Downstream code never constructs RunContext: it reads it from the
 * boundary API ({@code ToolExecutor.execute(call, ctx)} etc.). Forging
 * requires re-entering through a real entry point - which is the host's
 * trust boundary, not the tool's.
 * <p>
 * <b>Lifecycle event sink (Stage 7.1).</b> {@code eventSink} is the
 * explicit-propagation channel for {@link RunEvent}s: the entry adapter
 * hands it in at boundary construction, the loop pushes the eight
 * lifecycle facts into it, child contexts inherit it via
 * {@link #deriveChild} so a whole trace lands on one sink. Null = no
 * lifecycle telemetry (legacy behavior, bit-for-bit). This is the
 * mechanism of record; any ThreadLocal broadcaster stays a compatibility
 * convenience (RunEvent's own dispatch contract, Stage 1.3).
 * <p>
 * <b>Sensitive fields (roadmap 1.1: safe logging format).</b> {@code toString}
 * redacts userId and never prints the cancellation token: logs may carry
 * runId/traceId/tenantId freely (they are correlation keys, not
 * credentials), but full user identity stays out of logs by default.
 */
public record RunContext(
        String runId,
        String traceId,
        String tenantId,
        String userId,
        String agentId,
        String workflowId,
        String channelId,
        String parentRunId,
        Instant startedAt,
        Instant deadline,
        CancellationToken cancellationToken,
        RunBudget budget,
        IdempotencyScope idempotencyScope,
        RunIdentity identity,
        Set<String> capabilities,
        Consumer<RunEvent> eventSink
) {

    /** A context with no tenant/user identity (tests, local one-shots). */
    public static RunContext create() {
        return builder().build();
    }

    /** Standard entry: system-generated runId + traceId when absent. */
    public static RunContext.Builder builder() {
        return new Builder();
    }

    /**
     * Derive a child context for a nested execution (agent-in-workflow,
     * workflow node running an inner agent, sub-run). Shares traceId,
     * tenant/user identity, capabilities and idempotency scope; the child
     * gets its own runId and parentRunId pointing back here. Deadline and
     * cancellation propagate unchanged.
     */
    public RunContext deriveChild(String childAgentId) {
        return new Builder(this)
                .parentRunId(runId)
                .agentId(childAgentId)
                .generateIds()
                .build();
    }

    /** Copy helper for hosts adjusting one field at their own entry boundary. */
    public RunContext.Builder toBuilder() {
        return new Builder(this);
    }

    /** Deadline expired? (false when no deadline configured). */
    public boolean isDeadlineExceeded() {
        return deadline != null && Instant.now().isAfter(deadline);
    }

    /** Milliseconds left until the deadline; -1 when unlimited. */
    public long deadlineRemainingMs() {
        if (deadline == null) {
            return -1;
        }
        return Math.max(0, deadline.toEpochMilli() - System.currentTimeMillis());
    }

    /**
     * Structured cancellation + deadline check for boundaries.
     * Throws RunCancelledException on cancel hit, RunDeadlineException on
     * deadline hit. Both carry structured FailureKind, never free text.
     */
    public void checkAlive() {
        if (cancellationToken != null) {
            cancellationToken.check();
        }
        if (isDeadlineExceeded()) {
            throw new RunDeadlineException("Run deadline exceeded at boundary check");
        }
    }

    /** Safe-for-logs rendering: correlation keys only, userId redacted. */
    public String toLogString() {
        return "RunContext[runId=" + runId
                + ", traceId=" + traceId
                + ", tenantId=" + tenantId
                + ", agentId=" + agentId
                + "]";
    }

    @Override
    public String toString() {
        return "RunContext[runId=" + runId
                + ", traceId=" + traceId
                + ", tenantId=" + tenantId
                + ", agentId=" + agentId
                + ", userId=REDACTED"
                + ", deadline=" + deadline
                + "]";
    }

    // ============ Builder ============

    public static final class Builder {
        private String runId;
        private String traceId;
        private String tenantId;
        private String userId;
        private String agentId;
        private String workflowId;
        private String channelId;
        private String parentRunId;
        private Instant deadline;
        private CancellationToken cancellationToken;
        private RunBudget budget;
        private IdempotencyScope idempotencyScope;
        private RunIdentity identity;
        private Set<String> capabilities = Set.of();
        private java.util.function.Consumer<RunEvent> eventSink;

        private Builder() {
        }

        private Builder(RunContext from) {
            this.runId = from.runId;
            this.traceId = from.traceId;
            this.tenantId = from.tenantId;
            this.userId = from.userId;
            this.agentId = from.agentId;
            this.workflowId = from.workflowId;
            this.channelId = from.channelId;
            this.parentRunId = from.parentRunId;
            this.deadline = from.deadline;
            this.cancellationToken = from.cancellationToken;
            this.budget = from.budget;
            this.idempotencyScope = from.idempotencyScope;
            this.identity = from.identity;
            this.capabilities = from.capabilities;
            this.eventSink = from.eventSink;
        }

        public Builder runId(String runId) {
            this.runId = runId;
            return this;
        }

        public Builder traceId(String traceId) {
            this.traceId = traceId;
            return this;
        }

        public Builder tenantId(String tenantId) {
            this.tenantId = tenantId;
            return this;
        }

        public Builder userId(String userId) {
            this.userId = userId;
            return this;
        }

        public Builder agentId(String agentId) {
            this.agentId = agentId;
            return this;
        }

        public Builder workflowId(String workflowId) {
            this.workflowId = workflowId;
            return this;
        }

        public Builder channelId(String channelId) {
            this.channelId = channelId;
            return this;
        }

        public Builder parentRunId(String parentRunId) {
            this.parentRunId = parentRunId;
            return this;
        }

        public Builder deadline(Instant deadline) {
            this.deadline = deadline;
            return this;
        }

        public Builder cancellationToken(CancellationToken token) {
            this.cancellationToken = token;
            return this;
        }

        public Builder budget(RunBudget budget) {
            this.budget = budget;
            return this;
        }

        public Builder idempotencyScope(IdempotencyScope scope) {
            this.idempotencyScope = scope;
            return this;
        }

        public Builder identity(RunIdentity identity) {
            this.identity = identity;
            return this;
        }

        public Builder capabilities(Set<String> capabilities) {
            this.capabilities = capabilities == null ? Set.of() : Set.copyOf(capabilities);
            return this;
        }

        /** Lifecycle event sink (Stage 7.1): the loop pushes RunEvents here. */
        public Builder eventSink(java.util.function.Consumer<RunEvent> eventSink) {
            this.eventSink = eventSink;
            return this;
        }

        /** Fresh runId + traceId (used by deriveChild). */
        private Builder generateIds() {
            this.runId = UUID.randomUUID().toString();
            // traceId intentionally inherited: parent and child share one trace
            return this;
        }

        public RunContext build() {
            String id = runId != null ? runId : UUID.randomUUID().toString();
            String trace = traceId != null ? traceId : UUID.randomUUID().toString();
            return new RunContext(
                    id,
                    trace,
                    tenantId,
                    userId,
                    agentId,
                    workflowId,
                    channelId,
                    parentRunId,
                    Instant.now(),
                    deadline,
                    cancellationToken,
                    budget,
                    idempotencyScope,
                    identity,
                    capabilities,
                    eventSink);
        }
    }
}
