spring:
  profiles:
    active: dev
  application:
    name: ancient_prose
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=100,maximumSize=200,expireAfterWrite=5m

  datasource:
    hikari:
      minimum-idle: 8
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  quartz:
    job-store-type: memory
    auto-startup: true
    startup-delay: 0
    wait-for-jobs-to-complete-on-shutdown: true
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: scheduler
            instanceId: AUTO
          threadPool:
            threadCount: 25
            threadPriority: 5
            class: org.quartz.simpl.SimpleThreadPool

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  file:
    path: ./logs
  level:
    com:
      baomidou:
        mybatisplus: debug
      iwj:
        ancient:
          prose: debug