package io.github.qwzhang01.agent.orchestrator;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.Objects;
import java.util.UUID;

/**
 * A self-contained unit of work handed to an {@link AgentWorker} (Stage 11 M11.1).
 * <p>
 * Design principle (D3 of the Stage 11 architecture): message passing over shared
 * state. A task carries everything the worker needs -- payload in, result out.
 * Workers never see each other's state; results are merged only at the
 * {@code ResultAggregator} single point.
 * <p>
 * The two trailing fields are execution constraints consumed by the supervisor
 * (M11.3): {@code timeoutMs} and {@code maxRetries}. Workers themselves execute
 * once per call; retry/timeout/cancel are orchestration policies, not worker logic.
 *
 * @param taskId     unique task identifier (auto-generated by the factories)
 * @param workerName target worker's name
 * @param taskType   what kind of task (e.g. "research", "review") -- used for
 *                   skill-based routing (M11.4)
 * @param payload    free-form task data; convention: a "prompt" text field for
 *                   prompt-driven workers
 * @param timeoutMs  execution timeout, 0 = unlimited (M11.3)
 * @param maxRetries retry budget on failure, 0 = no retry (M11.3)
 */
public record WorkerTask(
        String taskId,
        String workerName,
        String taskType,
        JsonNode payload,
        long timeoutMs,
        int maxRetries
) {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    public WorkerTask {
        Objects.requireNonNull(taskId, "taskId must not be null");
        Objects.requireNonNull(workerName, "workerName must not be null");
        if (timeoutMs < 0) {
            throw new IllegalArgumentException("timeoutMs must be >= 0");
        }
        if (maxRetries < 0) {
            throw new IllegalArgumentException("maxRetries must be >= 0");
        }
    }

    /**
     * Create a prompt-style task with an auto-generated id, no timeout, no retry.
     */
    public static WorkerTask of(String workerName, String taskType, String prompt) {
        return new WorkerTask(UUID.randomUUID().toString(), workerName, taskType,
                MAPPER.createObjectNode().put("prompt", prompt), 0, 0);
    }

    /**
     * Create a task from an arbitrary JSON payload with an auto-generated id.
     */
    public static WorkerTask of(String workerName, String taskType, JsonNode payload) {
        return new WorkerTask(UUID.randomUUID().toString(), workerName, taskType,
                payload, 0, 0);
    }

    /**
     * The prompt text (payload's "prompt" field), or null if this task has no prompt.
     */
    public String prompt() {
        return payload != null && payload.path("prompt").isTextual()
                ? payload.get("prompt").asText() : null;
    }
}
